#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
# add this next step together after investigating htmlproofer gem
# bundle exec htmlproofer ./_site --allow-hash-href --check-html --disable-external
